name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: windows-latest
    
    steps:
    - name: addmodules
      uses: actions/checkout@v3
      with:
       submodules: 'true'
       
    - name: run
      run: ./compile.bat 1
