name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  a:
    runs-on: windows-latest
    steps:
      - name: submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'
  
  build:
    runs-on: windows-latest
    steps:
    - name: compile
      run: ./compile.bat
